spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Customer

  zipkin:
    base-url: http://localhost:9411/

  application:
    name: customer-mongo


server:
  port: 8060
  management:
    endpoints:
      web:
        exposure:
          include:
            - "*"
      endpoint:
        health:
          show-details: always

feign:
  circuitbreaker:
    enabled: true
